### PR TITLE
MRIID-89 Added cypress tests for covid projections chart 

### PR DESCRIPTION
**Pull request by fernandodonaire**
Can be tested by running the Cypress tests in the CLI using command `npm run cypress:cli` or by running the interactive test runner using command `npm run cypress:gui` and clicking on the `CovidProjectionsChart.js` integration file.

### CODE REVIEW

**Comment by shaileshmahajan** [comment]
@fernandodonaire For some reason the timeout in the test is insufficient. I actually tried with 40seconds, but the test  still fails. I think we need to take a look at it, Could be my machine, but again we dont know how the github action will react timewise.

image

**Comment by fernandodonaire** [comment]
> @fernandodonaire For some reason the timeout in the test is insufficient. I actually tried with 40seconds, but the test still fails. I think we need to take a look at it, Could be my machine, but again we dont know how the github action will react timewise.

> On the browser, I do see the API returning response real quick in 2 seconds

Hey @shaileshmahajan , that's interesting. I just re-ran the Cypress GitHub action for this PR and it ran without issues. Can you please confirm that you pulled down the latest changes and that you have this exact environment variable in your `.env`? 

`REACT_APP_BACKEND_URL: https://gtwn1uelqb.execute-api.us-east-1.amazonaws.com/dev/api/`

From the output screenshot you sent, it looks like Cypress is not able to intercept any request sent to `https://gtwn1uelqb.execute-api.us-east-1.amazonaws.com/dev/api/projections` and this is why it is hanging until it times out.

**Comment by fernandodonaire** [comment]
> @fernandodonaire Ahh, that could be it. Can we change the URL to https://86an564ru5.execute-api.us-east-1.amazonaws.com/dev/api/. This is the new URL from new AWS account. The other URLS will be torn out by Sudheer in upcoming days.

@shaileshmahajan Aha! I just updated the API URL for the tests. Could you please pull down these changes and try again?

**Comment by shaileshmahajan** [comment]
@fernandodonaire Works great. Thanks!
image

**Review by shaileshmahajan — APPROVED** [review]

**Comment by fernandodonaire** [comment]
Thanks for the review @shaileshmahajan !

**Pull request merged**
