### PR TITLE
MRIID - 67 Added projections banner

### PR DESCRIPTION
**Pull request by fernandodonaire**
Added banner to top of app when projections are enabled. This banner will only be displayed when projections are enabled. 

NOTE: We still need to add some links to the banner, but wanted to create the component and we can add those later. 

Screen Shot 2021-02-26 at 1 14 30 PM

### CODE REVIEW

**Review by rachelchorney — APPROVED** [review]
I was originally thinking the banner should stay across the top on all screens once you have confirmed you want to turn on projections (instead of only appearing when you view projection data). Is this an easy change to make later if we decide it should stay on? If it stays on all screens the text could change slightly to say something like "Some of the data on this site is for research only".

**Comment by fernandodonaire** [comment]
> I was originally thinking the banner should stay across the top on all screens once you have confirmed you want to turn on projections (instead of only appearing when you view projection data). Is this an easy change to make later if we decide it should stay on? If it stays on all screens the text could change slightly to say something like "Some of the data on this site is for research only".

That should be a pretty quick change actually! Yeah, if we want the banner to stay across the top on all screens I can just make that update now.

**Comment by rachelchorney** [comment]
@fernandodonaire Okay, if you can make the change now that would be great! Thanks!

**Comment by fernandodonaire** [comment]
@rachelchorney , I just pushed some updates for this which will keep the banner open when viewing any type of data after the user clicks 'Confirm' on the projections popup: 

Screen Shot 2021-03-01 at 9 46 58 AM

**Comment by rachelchorney** [comment]
@fernandodonaire Looks great! Thanks!

**Comment by fernandodonaire** [comment]
Thanks for the review!

**Pull request merged**
