### PR TITLE
MRIID-74 Added risk data radio button

### PR DESCRIPTION
**Pull request by fernandodonaire**
Added 'Risk' radio button to the Sidebar to display the ebola risk map. This button is only rendered when the "Ebola Outbreak" is selected.

Screen Shot 2021-02-25 at 1 10 16 PM

### CODE REVIEW

**Review by rachelchorney — CHANGES_REQUESTED** [review]
I'm getting a map box error:
image

**Comment by fernandodonaire** [comment]
> I'm getting a map box error:
> image

I think you might be missing the mapbox key in your .env file. Can you please copy the mapbox key from the `env.sample` file into your `.env` file, then restart the app?

**Review by rachelchorney — APPROVED** [review]
It's working now. Thank you!

**Comment by fernandodonaire** [comment]
Thanks for the review @rachelchorney !

**Pull request merged**
