### PR TITLE
MRIID 66 Add projections data popup

### PR DESCRIPTION
**Pull request by fernandodonaire**
Added popup for when a user tries to view projections data. In order to view the projections data, they need to click on the 'Confirm' button in the popup.

Screen Shot 2021-02-22 at 11 53 00 AM

Can be tested by: 

1) Running the app locally using `npm start`.
2) Clicking on the 'Projected cases' radio button.
3) This will display the popup. Clicking on "Confirm" will allow you to see the projections data. Clicking on "Cancel" will just close the popup.

Also wrote Cypress tests can can be run by: 

1) Running the app locally using `npm start`.
2) On another terminal window, entering `npx cypress open`. 
3) On the browser window that is opened, clicking on the `ProjectionsPopup.js` integration to run it.

### CODE REVIEW

**Review by rachelchorney — CHANGES_REQUESTED** [review]
When I tested this out the pop up opened every time I switched back to projected cases. The pop up should only appear the first time you click on projected cases. Once you have confirmed that you want to view projected data, you should not see the pop up again.

**Comment by fernandodonaire** [comment]
> When I tested this out the pop up opened every time I switched back to projected cases. The pop up should only appear the first time you click on projected cases. Once you have confirmed that you want to view projected data, you should not see the pop up again.

Good call. I'll update that.

**Comment by fernandodonaire** [comment]
Hey @rachelchorney , I updated this so that you only need to confirm this once 🙂

**Review by SpencerMarks-IDHA — APPROVED** [review]

**Review by rachelchorney — APPROVED** [review]
This looks great!

**Comment by fernandodonaire** [comment]
Thanks @SpencerMarks-IDHA and @rachelchorney !

**Pull request merged**
