### PR TITLE
MRIID-81 Styled components clean up

### PR DESCRIPTION
**Pull request by fernandodonaire**
1) Went through all of the styled components in the `styled-components` directory and if they are only used on a single component, moved these styled components to a `styles.js` file in the parent component's folder (for example `src/components/Sidebar/styles.js`). 

2) Removed styled components that we were no longer using.

3) Renamed the `styled-components` directory to `SharedStyledComponents`. This directory will only have the styled components that are used by more than one component.

This can be tested by running the app locally and clicking around. The app should function the same as it did before. 

You can also run the unit tests using `npm test` then clicking the `a` key to run all tests.

### CODE REVIEW

**Comment by shaileshmahajan** [comment]
@fernandodonaire . WOW. Awesome changes 🥇 

1. To be honest, I did not go over each of the 82 files in details. I did do extensive testing on frontend  site and did not encounter any issues.

2. Suggestion - I like styles being imported as `import * as Styled from ""` and then followed by using `<Styled.PageWrapper>` as oppose to `import {PageWrapper} from ./styles`. I think it's easier to know that this is a styled component as oppose to regular react component.  May be its just me :). But in future, if we agree we can follow that sort of naming convention.

**Review by shaileshmahajan — APPROVED** [review]

**Comment by shaileshmahajan** [comment]
@fernandodonaire (Sorry After approval noticed something) I do see the following, if it was preexisting, we can ignore it
image

**Review by rachelchorney — APPROVED** [review]
This looks great! Thanks for doing this. I tested out the site and everything looked good.

**Comment by fernandodonaire** [comment]
Thanks for the reviews @shaileshmahajan and @rachelchorney ! Yeah I've been wanting to clear those up for a while! 😄 

That's a good point about the styled components imports @shaileshmahajan . Yeah maybe we can decide how we want to do this moving forward and we can update them then.

**Pull request merged**
