### PR TITLE
Covid outbreak additions

### PR DESCRIPTION
**Pull request by fernandodonaire**
Merging all of the covid outbreak additions to the `development` branch.

### CODE REVIEW

**Comment by fernandodonaire** [comment]
Hey @SpencerMarks-IDHA , this is just merging all of the Covid changes to the `development` branch. Could you please approve and then I'll squash and merge?

**Comment by fernandodonaire** [comment]
You have already reviewed these changes on the `covid-outbreak-additions` branch 😄

**Comment by fernandodonaire** [comment]
Hey @SpencerMarks-IDHA can you please approve this PR for merging the Covid changes into the `development` branch? This is all code that you've reviewed in the past except for the changes in commit b923e3f which are new.

**Review by SpencerMarks-IDHA — APPROVED** [review]

**Comment by fernandodonaire** [comment]
Thanks @SpencerMarks-IDHA !

**Pull request merged**
