### PR TITLE
updated date range slider labels

### PR DESCRIPTION
**Pull request by rachelchorney**
Ticket: http://jiraprod.tch.harvard.edu/browse/MRIID-78

I need help getting the selected start and end date values to display in the tooltip that appears when you hover over the left or right slider handle.

image

### CODE REVIEW

**Comment by fernandodonaire** [comment]
Hey @rachelchorney , I pushed some changes and you can now see the selected dates when you hover over the slider labels.

When you hover over the second slider label:

Screen Shot 2021-03-17 at 9 18 58 AM

When you hover over the first slider label:

Screen Shot 2021-03-17 at 9 19 19 AM

**Comment by rachelchorney** [comment]
@fernandodonaire Thank you for doing this. It looks great!

**Comment by fernandodonaire** [comment]
> @fernandodonaire Thank you for doing this. It looks great!

No problem! I requested a review from Shailesh since we both worked on it 🙂

**Comment by shaileshmahajan** [comment]
@fernandodonaire @rachelchorney Awesome work!!. Tests passed . I also verified following
- Hovering over the slider handles should display the selected value.
- The static labels to the left and right of the slider should display the min and max date for the outbreak not change

**Pull request merged**
