### PR TITLE
MRIID-45 Covid death projections chart

### PR DESCRIPTION
**Pull request by fernandodonaire**
Added Covid death projections chart. The data that is displayed here are the "50" and "97.5" confidence interval values for the last 7 days of death projections we have for the selected country. This prevents a potential issue of projections data not being update every week.

We are also showing the observed deaths starting 14 days prior to the last day of death projections for the selected country.

Can be tested by: 

1) Running the app locally using `npm start`.
2) Selecting the "COVID 19" outbreak in the sidebar.
3) Selecting different countries in the sidebar.

This is what is looks like when you select a country that has projections data: 

Screen Shot 2021-03-10 at 10 23 02 AM

When 'All' countries are selected: 

Screen Shot 2021-03-10 at 10 24 11 AM

When the selected country doesn't have death projections data: 

Screen Shot 2021-03-10 at 10 24 49 AM

### CODE REVIEW

**Comment by rachelchorney** [comment]
@fernandodonaire This is looking good. I think the black line should switch to green once we are viewing projected deaths for the week ahead and we should include projected deaths in the legend. Similar to this mock up:
image

**Review by rachelchorney — CHANGES_REQUESTED** [review]
The observed death count should stop when you the projected deaths interval starts. Please see my other comment for more details.

**Comment by fernandodonaire** [comment]
> The observed death count should stop when you the projected deaths interval starts. Please see my other comment for more details.

Thanks! I'll see how we can make that change.

**Review by rachelchorney — APPROVED** [review]
This looks great!

**Comment by fernandodonaire** [comment]
> This looks great!

Awesome! Thanks!

**Pull request merged**
