### PR TITLE
added material ui theme and updated sidebar style

### PR DESCRIPTION
**Pull request by rachelchorney**
- Added a theme file to override default material ui styles
- Updated style of sidebar and select component

image

### CODE REVIEW

**Review by fernandodonaire — CHANGES_REQUESTED** [review]
Hey @rachelchorney , this is looking really good! Just a couple of things: 

1) The test here (src/components/Select/__tests__/Select.test.js) is failing because the props for the `Select` component changed. To fix this, you just need to pass the new props to the `Select` component in the test. So like this: 

```
test("renders component without crashing", () => {
  shallow(
    <Select optionsCurrent={["COVID 19"]} optionsPast={["Ebola Outbreak"]} />
  );
});
``` 
2) I noticed that when you switch between outbreaks, the select remains in focus (with a blue line under it) until you click somewhere else on the page. Is that something we want or should the focus be removed once someone makes a selection? 

Screen Shot 2021-02-04 at 2 18 18 PM

**Comment by rachelchorney** [comment]
@fernandodonaire Thank you for letting me know how to fix that test. I was trying to figure it out and I got stuck!

**Comment by rachelchorney** [comment]
@fernandodonaire Yes, the focus should be removed. I'm also planning to remove the blue line so it won't be there at all (even on focus). I will add a new focus style that matches the rest of the layout.

**Comment by fernandodonaire** [comment]
> @fernandodonaire Yes, the focus should be removed. I'm also planning to remove the blue line so it won't be there at all (even on focus). I will add a new focus style that matches the rest of the layout.

Sounds good! Kudos for finding out how to get around the MUI styles by the way!

**Review by fernandodonaire — APPROVED** [review]

**Pull request merged**
