### PR TITLE
Added risk/snapshot view toggle

### PR DESCRIPTION
**Pull request by fernandodonaire**
Screen Shot 2020-11-11 at 3 10 18 PM

This can be tested by: 

1) Pulling down this branch.
2) Running the app locally.
3) On the Home page, clicking on the risk/snapshot view toggle on the map.

### CODE REVIEW

**Comment by rachelchorney** [comment]
@fernandodonaire Clicking on the toggle clears the content in the left sidebar. The map view does not change. Is this the expected behavior?

image

**Comment by fernandodonaire** [comment]
> @fernandodonaire Clicking on the toggle clears the content in the left sidebar. The map view does not change. Is this the expected behavior?

Hey @rachelchorney , yeah that is expected for now. I still need to add the "Risk" map and risk-specific content to the sidebar, but I'll do that in this ticket: http://jiraprod.tch.harvard.edu/browse/MRIID-23

**Review by rachelchorney — APPROVED** [review]
Looks good!

**Comment by fernandodonaire** [comment]
Thanks @rachelchorney !

**Pull request merged**
